name: Vyapr Cron

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:        # lets you run it manually from GitHub UI

jobs:
  call-vyapr:
    runs-on: ubuntu-latest
    steps:
      - name: Ping marker event (proves this workflow ran)
        run: |
          curl -s -X POST "https://vyapr-reset-5rly.vercel.app/api/events/log" \
            -H "Content-Type: application/json" \
            -d '{
                  "event": "cron.gha.ping",
                  "provider_slug": "amitjain0626",
                  "source": {
                    "runner": "gha",
                    "run_id": "'"$GITHUB_RUN_ID"'",
                    "run_number": "'"$GITHUB_RUN_NUMBER"'",
                    "repo": "'"$GITHUB_REPOSITORY"'"
                  }
                }' | jq

      - name: Orchestrate campaigns (normal mode; respects quiet hours & caps)
        run: |
          curl -s -X POST "https://vyapr-reset-5rly.vercel.app/api/cron/campaigns?slug=amitjain0626" | jq

      # Optional: fire test-mode once per run to guarantee at least one verifiable send
      - name: Orchestrate campaigns (test mode; safe, no caps)
        run: |
          curl -s -X POST "https://vyapr-reset-5rly.vercel.app/api/cron/campaigns?slug=amitjain0626&test=1" | jq
